# The Site Configuration

# Use custom theme instead of Chirpy
theme: 

# Basic site info
title: James Chang
tagline: Musician, Developer, Creator
description: >- 
  Personal website of James Chang featuring music, development, art, chess, cubing, and more

# URL settings
url: "https://jameszjwchang.github.io"
baseurl: "" # No base URL since Jekyll manages the entire site now

# Favicon settings
favicon: "/assets/img/favicon.ico"

# Author information
author:
  name: James Chang
  email: jameszjwchang@outlook.com

# Social links
github:
  username: jameszjwchang
twitter:
  username: your_twitter_handle
social:
  name: James Chang
  links:
    - https://github.com/jameszjwchang
    - https://www.linkedin.com/in/your_linkedin
    - https://www.youtube.com/channel/your_channel

# Site structure
permalink: /blog/:title/

# Blog features
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  tabs:
    output: true
    sort_by: order
  interests:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
  - scope:
      path: "_interests"
      type: interests
    values:
      layout: interest
  - scope:
      path: "_tabs"
    values:
      layout: page

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

# Other settings remain the same as before
lang: en
timezone:

webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

pageviews:
  provider: 

theme_mode: 

cdn:

avatar: "/assets/img/avatars/profile.jpg"

social_preview_image: 

toc: true

comments:
  provider: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id:
    category:
    category_id:
    mapping: 
    strict: 
    input_position: 
    lang: 
    reactions_enabled: 

assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
