# Site Configuration
title: James Chang
tagline: Musician, Developer, Creator
description: Personal website of James Chang featuring music, development, art, and more

# URL settings
url: "https://jameszjwchang.github.io"
baseurl: ""

# Author information
author:
  name: James Chang
  email: jameszjwchang@outlook.com

# Social links
github:
  username: jameszjwchang

# Site structure
permalink: /blog/:title/

# Blog features
paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: "<!--more-->"

# Collections
collections:
  tabs:
    output: true
    sort_by: order
  interests:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
  - scope:
      path: "_interests"
      type: interests
    values:
      layout: interest
  - scope:
      path: "_tabs"
    values:
      layout: page

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
lang: en
favicon: "/assets/img/favicon.ico"
avatar: "/assets/img/avatars/profile.jpg"

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
